using System.Collections;
public class Bank
{
    private static Hashtable accounts = new Hashtable();
    private Bank()
    {
    }
        static public long CreateAccount()
        {
            BankAccount newAcc = new BankAccount();
            long accNo = newAcc.Number();
            accounts[accNo] = newAcc;
            return accNo;
        }
        static public long CreateAccount(AccountType aType, decimal aBal)
        {
            BankAccount newAcc = new BankAccount();
            long accNo = newAcc.Number();
            accounts[accNo] = newAcc;
            return accNo;
        }
        static public long CreateAccount(AccountType aType)
        {
            BankAccount newAcc = new BankAccount();
            long accNo = newAcc.Number();
            accounts[accNo] = newAcc;
            return accNo;
        }
        static public long CreateAccount(decimal aBal)
        {
            BankAccount newAcc = new BankAccount();
            long accNo = newAcc.Number();
            accounts[accNo] = newAcc;
            return accNo;
        }
        static public bool CloseAccount(long accNo)
        {
            BankAccount closing = (BankAccount)accounts[accNo];
            if (closing != null)
            {
                accounts.Remove(accNo);
                closing.Dispose();
                return true;
            }
            else
            {
                return false;
            }
        }
        static public BankAccount GetAccount(long accNo)
        {
            return (BankAccount)accounts[accNo];
        }
}    